# Generated by Django 3.2.7 on 2021-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
