# Generated by Django 3.2.7 on 2021-11-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211103_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteer_area',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
