# Generated by Django 3.2.7 on 2021-11-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent1name', models.CharField(max_length=500)),
                ('parent2name', models.CharField(blank=True, max_length=500)),
                ('homephone', models.CharField(max_length=500)),
                ('businessphone', models.CharField(max_length=500)),
                ('mailingaddress', models.CharField(max_length=1000)),
                ('emailaddress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteerareaname', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('familyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.family')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventdescription', models.CharField(max_length=1000)),
                ('eventdate', models.DateField()),
                ('eventstart', models.TimeField()),
                ('eventend', models.TimeField()),
                ('volunteernumber', models.IntegerField()),
                ('eventperiod', models.CharField(max_length=500)),
                ('volunteerarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.volunteerarea')),
            ],
        ),
    ]
