# Generated by Django 3.2.7 on 2021-11-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_family_volunteerarea_volunteerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerarea',
            name='familyid',
        ),
    ]
